### ISSUE TITLE
chore: Move `components` folder to GC-Proto

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/design-system#131] opened 2022-08-19 19:51 UTC
components/alerts-demo.html
components/alerts-rationale.html
components/alerts.html
components/alignment.html
components/badges.html
components/bands.html
components/bar-chart-demo.html
components/bar-chart-rationale.html
components/bar-chart.html
components/borders.html
components/breadcrumb.html
components/buttons-2.html
components/buttons-3.html
components/buttons-demo.html
components/buttons-guidelines-2.html
components/buttons-rationale-2.html
components/buttons-rationale.html
components/buttons.html
components/calendar.html
components/canada-wordmark.html
components/cards.html
components/charts-graphs.html
components/checkboxes-demo.html
components/checkboxes-rationale.html
components/checkboxes.html
components/code-text.html
components/contact-form-demo.html
components/contact-form-rationale.html
components/contact-form.html
components/contextual-feature.html
components/data-picture.html
components/date-modified.html
components/date-picker.html
components/definition-list-demo.html
components/definition-list-rationale.html
components/definition-list.html
components/demos/alerts/beta/danger-code.html
components/demos/alerts/beta/danger.html
components/demos/alerts/beta/info-code.html
components/demos/alerts/beta/info.html
components/demos/alerts/beta/success-code.html
components/demos/alerts/beta/success.html
components/demos/alerts/beta/warning-code.html
components/demos/alerts/beta/warning.html
components/demos/alerts/wet4/danger-code.html
components/demos/alerts/wet4/info-code.html
components/demos/alerts/wet4/success-code.html
components/demos/alerts/wet4/warning-code.html
components/demos/buttons/wet4/basic-call-to-action.html
components/demos/buttons/wet4/basic-danger.html
components/demos/buttons/wet4/basic-link.html
components/demos/buttons/wet4/basic-primary.html
components/demos/buttons/wet4/basic-secondary.html
components/demos/buttons/wet4/block-call-to-action.html
components/demos/buttons/wet4/block-danger.html
components/demos/buttons/wet4/block-link.html
components/demos/buttons/wet4/block-primary.html
components/demos/buttons/wet4/block-secondary.html
components/demos/buttons/wet4/disabled-call-to-action.html
components/demos/buttons/wet4/disabled-danger.html
components/demos/buttons/wet4/disabled-link.html
components/demos/buttons/wet4/disabled-primary.html
components/demos/buttons/wet4/disabled-secondary.html
components/demos/buttons/wet4/group-primary.html
components/demos/buttons/wet4/group-secondary.html
components/demos/buttons/wet4/sizing-danger.html
components/demos/buttons/wet4/sizing-primary.html
components/demos/buttons/wet4/sizing-secondary.html
components/demos/checkboxes-radio-buttons-customisation.html
components/demos/contact-form/wet4/feedback-code.html
components/demos/contact-form/wet4/feedback.html
components/demos/contact-form/wet4/hybrid-code.html
components/demos/contact-form/wet4/hybrid.html
components/demos/contact-form/wet4/request-code.html
components/demos/contact-form/wet4/request.html
components/demos/definition-list/wet4/dl-basic-code.html
components/demos/definition-list/wet4/dl-basic.html
components/demos/definition-list/wet4/dl-horizontal-code.html
components/demos/definition-list/wet4/dl-horizontal-nb-code.html
components/demos/definition-list/wet4/dl-horizontal-nb.html
components/demos/definition-list/wet4/dl-horizontal.html
components/demos/dropdown/wet4/autocomplete-code.html
components/demos/dropdown/wet4/autocomplete.html
components/demos/dropdown/wet4/dropdown-code.html
components/demos/dropdown/wet4/dropdown.html
components/demos/link-description/wet4/dropdown-code.html
components/demos/link-description/wet4/dropdown.html
components/demos/link-description/wet4/link-description-1col-code.html
components/demos/link-description/wet4/link-description-1col.html
components/demos/link-description/wet4/link-description-2col-code.html
components/demos/link-description/wet4/link-description-2col.html
components/demos/link-description/wet4/link-description-3col-code.html
components/demos/link-description/wet4/link-description-3col.html
components/demos/link-description/wet4/link-description-sub-headings-code.html
components/demos/link-description/wet4/link-description-sub-headings.html
components/demos/link-description/wet4/sequenced-steps-code.html
components/demos/link-description/wet4/sequenced-steps.html
components/demos/lists/lists-customisation.html
components/demos/lists/wet4/list-link-default-code.html
components/demos/lists/wet4/list-link-default.html
components/demos/lists/wet4/list-link-mr-code.html
components/demos/lists/wet4/list-link-mr.html
components/demos/lists/wet4/list-link-toc-code.html
components/demos/lists/wet4/list-link-toc.html
components/demos/lists/wet4/list-ordered-default-code.html
components/demos/lists/wet4/list-ordered-default.html
components/demos/lists/wet4/list-ordered-lower-alpha-code.html
components/demos/lists/wet4/list-ordered-lower-alpha.html
components/demos/lists/wet4/list-ordered-lower-roman-code.html
components/demos/lists/wet4/list-ordered-lower-roman.html
components/demos/lists/wet4/list-ordered-upper-alpha-code.html
components/demos/lists/wet4/list-ordered-upper-alpha.html
components/demos/lists/wet4/list-ordered-upper-roman-code.html
components/demos/lists/wet4/list-ordered-upper-roman.html
components/demos/lists/wet4/list-unordered-code.html
components/demos/lists/wet4/list-unordered.html
components/demos/radio-buttons/beta/optional-code.html
components/demos/radio-buttons/beta/optional.html
components/demos/radio-buttons/beta/required-code.html
components/demos/radio-buttons/beta/required.html
components/demos/tables-MVP/alpha/basic-code.html
components/demos/tables-MVP/alpha/basic-filter-code.html
components/demos/tables-MVP/alpha/basic-filter-left-code.html
components/demos/tables-MVP/alpha/basic-filter-left.html
components/demos/tables-MVP/alpha/basic-filter-small.html
components/demos/tables-MVP/alpha/basic-filter.html
components/demos/tables-MVP/alpha/basic-left-code.html
components/demos/tables-MVP/alpha/basic-left.html
components/demos/tables-MVP/alpha/basic-small-code.html
components/demos/tables-MVP/alpha/basic-small.html
components/demos/tables-MVP/alpha/basic.html
components/demos/tables-MVP/alpha/striped-code.html
components/demos/tables-MVP/alpha/striped-filter-code.html
components/demos/tables-MVP/alpha/striped-filter-left-code.html
components/demos/tables-MVP/alpha/striped-filter-left.html
components/demos/tables-MVP/alpha/striped-filter-small.html
components/demos/tables-MVP/alpha/striped-filter.html
components/demos/tables-MVP/alpha/striped-left-code.html
components/demos/tables-MVP/alpha/striped-left.html
components/demos/tables-MVP/alpha/striped-small-code.html
components/demos/tables-MVP/alpha/striped-small.html
components/demos/tables-MVP/alpha/striped.html
components/demos/tables-MVP/css/responsive-tables-demo-only.css
components/demos/tables-MVP/wet4/basic-code.html
components/demos/tables-MVP/wet4/basic-filter-code.html
components/demos/tables-MVP/wet4/basic-filter.html
components/demos/tables-MVP/wet4/basic.html
components/demos/tables-MVP/wet4/striped-code.html
components/demos/tables-MVP/wet4/striped-filter-code.html
components/demos/tables-MVP/wet4/striped-filter.html
components/demos/tables-MVP/wet4/striped.html
components/demos/tables/alpha/basic-code.html
components/demos/tables/alpha/basic-filter-code.html
components/demos/tables/alpha/basic-filter-left-code.html
components/demos/tables/alpha/basic-filter-left.html
components/demos/tables/alpha/basic-filter-small.html
components/demos/tables/alpha/basic-filter.html
components/demos/tables/alpha/basic-left-code.html
components/demos/tables/alpha/basic-left.html
components/demos/tables/alpha/basic-small-code.html
components/demos/tables/alpha/basic-small.html
components/demos/tables/alpha/basic.html
components/demos/tables/alpha/striped-code.html
components/demos/tables/alpha/striped-filter-code.html
components/demos/tables/alpha/striped-filter-left-code.html
components/demos/tables/alpha/striped-filter-left.html
components/demos/tables/alpha/striped-filter-small.html
components/demos/tables/alpha/striped-filter.html
components/demos/tables/alpha/striped-left-code.html
components/demos/tables/alpha/striped-left.html
components/demos/tables/alpha/striped-small-code.html
components/demos/tables/alpha/striped-small.html
components/demos/tables/alpha/striped.html
components/demos/tables/css/responsive-tables-demo-only.css
components/demos/tables/wet4/basic-code.html
components/demos/tables/wet4/basic-filter-code.html
components/demos/tables/wet4/basic-filter.html
components/demos/tables/wet4/basic.html
components/demos/tables/wet4/striped-code.html
components/demos/tables/wet4/striped-filter-code.html
components/demos/tables/wet4/striped-filter.html
components/demos/tables/wet4/striped.html
components/demos/text-editing/wet4/cite-code.html
components/demos/text-editing/wet4/cite.html
components/demos/text-editing/wet4/deleted-code.html
components/demos/text-editing/wet4/deleted.html
components/demos/text-editing/wet4/emphasis-code.html
components/demos/text-editing/wet4/emphasis.html
components/demos/text-editing/wet4/highlighted-code.html
components/demos/text-editing/wet4/highlighted.html
components/demos/text-editing/wet4/redacted-code.html
components/demos/text-editing/wet4/redacted.html
components/demos/text-editing/wet4/strike-code.html
components/demos/text-editing/wet4/strike.html
components/dropdown-demo.html
components/dropdown-rationale.html
components/dropdown.html
components/equalize.html
components/expand-collapse-demo.html
components/expand-collapse-rationale.html
components/expand-collapse.html
components/favicon.html
components/link-description-demo.html
components/link-description-rationale.html
components/link-description.html
components/lists-demo.html
components/lists-rationale.html
components/lists.html
components/radio-buttons-demo.html
components/radio-buttons-rationale.html
components/radio-buttons.html
components/subway-navigation.html
components/tables-alpha-demo.html
components/tables-alpha.html
components/tables-demo-fr.html
components/tables-demo.html
components/tables-rationale.html
components/tables.html
components/text-editing-demo.html
components/text-editing-rationale.html
components/text-editing.html

to move to GC-Proto Experimental
link to GC-Proto : https://github.com/gc-proto/experimental/issues/9

**Comment by delisma** [comment] 2022-08-20 11:38
Duplicate of #122

**Closed as completed** 2022-08-23 20:12 UTC
Labels: duplicate
